export enum TokenStatusEnum {
    REQUESTED='REQUESTED',
    CANCELLED_REQUESTED='CANCELLED_REQUESTED',
    REJECTED_REQUEST='REJECTED_REQUEST',
    PENDING_TOKEN='PENDING_TOKEN',
    CANCELLED_TOKEN='CANCELLED_TOKEN',
    REJECTED_TOKEN='REJECTED_TOKEN',
    COMPLETED_TOKEN='COMPLETED_TOKEN'
}
export enum UserTypeEnum {
   ONLINE='ONLINE',
   OFFLINE='OFFLINE'
}